name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare cargo directory
        run: sudo mkdir -p ~/.cargo && sudo chown -R $(whoami):$(id -ng) ~/.cargo/

      - name: Cache cargo directory
        uses: actions/cache@v1
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache target directory
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache toolchains-directory
        uses: actions/cache@v1
        with:
          path: ~/.rustup/toolchains
          key: ${{ runner.os }}-cargo-toolchains-${{ hashFiles('**/rust-toolchain') }}

      - name: Install Components
        run: rustup component add clippy rustfmt && cargo install cargo-audit

      - name: Check & Test
        run: |
          cargo fmt -- --check \
            && cargo audit \
            && cargo clippy -- -D warnings \
            && cargo test \
            && docker-compose up -d db \
            && cargo test -- --ignored
