name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup component add clippy rustfmt
      - run: cargo clippy -- -D warnings
      - run: cargo fmt -- --check
